### ISSUE TITLE
Add alertMaximumDelay defaults to Utterance subtypes?

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#11]
While working on Molarity, I was fuzzing the a11y view and found the one `ValueChangeUtterance` never alerted because the slider kept moving forever. I wonder if we should bake in defaults for Utterance, ValueChangeUtterance, and ActivationUtterance so that we get an alert no matter what every 5 seconds? 10 seconds? 

I see that the option isn't being used at all. What do you think @jessegreenberg?

**Comment by jessegreenberg** [comment]
Fuzzing creates an interesting case here. In my opinion this isn't concerning and is the expected behavior for  `alertStableDelay` and ValueChangeUtterance. Theoretically if the user moves the slider forever, they will forever hear aria-valuetext over the alert. We would still want to give the screen reader a chance to finish reading the latest aria-valuetext before alerting to fulfill the workaround purpose of the long delay of ValueChangeUtterance.

**Comment by zepumph** [comment]
Alright. From that it seems like things are working as expected. If you feel like there is an action step for this issue please reopen.
