### ISSUE TITLE
Can we use utteranceQueue for PhET's self-voicing feature?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/utterance-queue#14]
I would like to be able to queue up web speech much like we do with utterance-queue. Can the queue be extended to support more than just output with aria-herald?

I brainstormed briefly with @zepumph and we discussed creating a way change the output method of utterance-queue with an option so that you could have one instance for aria and another instance for speech synthesis.

I am going to try it out.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/utterance-queue/commit/325044a5a42e58f8d64c80bf7efc5a56c7887691 is really the commit that implemented this.

To summarize changes - 

- utteranceQeue now takes an `announcer`, which implements an `announce` function. The `announce` function requests speech in some form (aria-live or web speech). This param is required.
- There is a new SelfVoicingUtterance with a couple of options that specifically control output for web-speech.

Everything else is pretty much the same. One thing I really wasn't sure about was the PhET-iO portion in utteranceQueue. TODO was added in the code. @zepumph can we review this today during meeting?

**Comment by zepumph** [comment]
I noticed that https://github.com/phetsims/utterance-queue/commit/325044a5a42e58f8d64c80bf7efc5a56c7887691 broke the a11y view because you got rid of `getAriaLiveContainer`. I know why and how, but it seems like we need to put a bit more thought into how we want that piece of the API to work. Maybe Display needs to take a bit more responsibility in managing AriaHerald, since we may make UtteranceQueue without a default announcer.

As it pertains to UtteranceQueue as a potential third-party library, it would be nice if we could make AriaHerald a default announcer. That may clear up the API in that case. I understand though that managing HTML elements really goes beyond the scope of Utterance queue. Maybe we could have UtteranceQueue implement an internal AriaHerald as the default announcer, and turn it into an option instead of a parameter. And if announcer was a public member (which it should be I think), then Display can just grab the elements as needed: 

```js
  this.utteranceQueue = new UtteranceQueue( ariaHerald, !this._accessible );
 const elements = this.utteranceQueue.announcer.ariaLiveContainer;
```

We can discuss more though. What you have may be better though.

**Comment by zepumph** [comment]
I created to https://github.com/phetsims/utterance-queue/issues/17 to specifically deal with the commented out phet-io event in utteranceQueue. Updating the todo now.

**Comment by zepumph** [comment]
Review comment I found while working on https://github.com/phetsims/scenery/issues/1183:

- [ ] RE: `* @param {Object} announcer` parameter in UtteranceQueue, can we make an `Announcer.js` abstract base type that outlines the interface that UtteranceQueue. This will give us a place to document this (with @abstract methods that can throw an assertion error until overridden), and also allows room for expanding if we want to increase the complexity of the `Announcer` interface.

**Comment by zepumph** [comment]
@jessegreenberg what is left for this issue? We have been using WebSpeaker in UtteranceQueue for a while now.

**Comment by zepumph** [comment]
> * can we make an `Announcer.js` abstract base type that outlines the interface that UtteranceQueue.

I thought this would be nice while working on https://github.com/phetsims/utterance-queue/issues/20, I think I'll take a stab at that.

**Comment by zepumph** [comment]
I made an `Announcer` base class, I had to swap EnabledComponent in VoicingManager to be composed to make it work. @jessegreenberg can you please review. Anything else here?
