### ISSUE TITLE
ResponsePatterns should be a class

### ISSUE THREAD

**Issue by zepumph** [phetsims/utterance-queue#32]

**Comment by zepumph** [comment]
(renamed from VoicingResponesPatterns in https://github.com/phetsims/utterance-queue/issues/31.

**Comment by jessegreenberg** [comment]
Im sure this is great, but can you please comment on why it is beneficial to be able to instantiate a ResponsePatterns?

**Comment by zepumph** [comment]
Only minor reasons as I worked on https://github.com/phetsims/utterance-queue/issues/31.

* I noticed that the type def in Voicing.setVoicingResponsePatterns takes only an object.
* I see that the primary way of creating response patterns is with ResponsePatterns.createResponsePatterns(). So to me the main question is really, "why is this factory-ish method better than just using a POJO, when we then need validation like `validatePatternKeys`. A POJO will make this more type safe (especially with typescript coming soon).

**Comment by zepumph** [comment]
Another minor thing. @jessegreenberg do you think we should rename to something that is singular?

**Comment by zepumph** [comment]
@jessegreenberg please review, and comment on the above thought about a rename.

**Comment by jessegreenberg** [comment]
The change looks good. A rename would also make sense. Was originally plural because the VoicingResponsePatterns object was expected to contain multiple objects like DEFAULT_RESPONSE_PATTERNS that might be helpful. Now that it is a class the reusable the reusable ones can be added statically like

```js
ResponsePattern.MODIFIED_RESPONSE_PATTERNS = new ResponsePattern( {
  //...
} )
```

It will contain a collection of response patterns, so maybe the name should be ResponsePatternCollection? With usages like

`this.voicingResponsePatterns = ResponsePatternCollection.MODIFIED_RESPONSE_PATTERNS`
```
this.voicingResponsePatterns = new ResponsePatternCollection( {
  nameContextHint: '{{NAME}}! {{CONTEXT}}? {{HINT}}...',
```

**Comment by zepumph** [comment]
Hows that?

**Comment by jessegreenberg** [comment]
Looks very good, thanks for this improvement! I like how this looks when overriding the default patterns
```js
      voicingResponsePatternCollection: new ResponsePatternCollection( {
        nameObjectHint: '{{OBJECT}}, {{NAME}}, {{HINT}}',
        nameObject: '{{OBJECT}}, {{NAME}}'
      } )
```
