### ISSUE TITLE
ariaHerald can't depend on scenery

### ISSUE THREAD

**Issue by twant** [phetsims/utterance-queue#4]
...because scenery depends on utterance-queue.

**Comment by zepumph** [comment]
Above @twant and I said "can't," but in reality things are working as is. AriaHerald requires a file from scenery, and as a result, `SCENERY` is the path for utterance-queue's config. When building as a standalong in #6, we found that on the namespace only the needed scenery files were being required and stored. In PhET sims we don't worry about this at all, because scenery will always be a dependency for them. From these two thoughts we feel good closing, and recognizing the dependency that utterance-queue has on scenery.

Again, this has been working in phet sims for a few weeks now, and recent work in #6 makes us confident it will be alright as a standalone library. Closing
