### ISSUE TITLE
Type casting SpeechSynthesisAnnouncer.enabledProperty is potentially buggy

### ISSUE THREAD

**Issue by chrisklus** [phetsims/utterance-queue#86]
In the TypeScript channel, I asked about a type error I'm getting in WebStorm that is not showing up in pre-commit hooks:

![image](https://user-images.githubusercontent.com/5618316/179866460-1d4ee27c-460b-4d66-a33d-c3f18524b1bb.png)

[Chris Klusendorf](https://app.slack.com/team/UBHLGT5C2)
  [7:15 PM](https://phetsims.slack.com/archives/C029UG5BVU3/p1658272549212379)
has anyone run into a problem where Webstorm errors on .value = for an IProperty, but tsc is passing? 
[@Luisa](https://phetsims.slack.com/team/U022HCYBGUE)
 and I have experienced this in separate cases today
[Chris Malley](https://app.slack.com/team/U6EMFARV2)
  [7:20 PM](https://phetsims.slack.com/archives/C029UG5BVU3/p1658272801367969)
voicingManager.ts is a singleton of VoicingManager, which extends SpeechSynthesisAnnouncer.  And there’s some hackery in SpeechSynthesisAnnouncer:
230 this.enabledProperty = this.enabledComponentImplementation.enabledProperty as IProperty<boolean>;
I wouldn’t be surprised if that is confusing WebStorm.
[7:21](https://phetsims.slack.com/archives/C029UG5BVU3/p1658272886235049)
And indeed, this.enabledComponentImplementation.enabledProperty is actually defined like this in EnabledComponent:
 public enabledProperty: IReadOnlyProperty<boolean>;
So it is in fact readonly. And casting it to IProperty<boolean> is super buggy.
[7:23](https://phetsims.slack.com/archives/C029UG5BVU3/p1658272991416689)
The cast was added in https://github.com/phetsims/utterance-queue/commit/d4149e203425e13870c04d5c927d03512577d9fa. I suggest a GitHub issue, assigned to the caster.

@samreid could you please take a look at your convienience?

**Comment by jessegreenberg** [comment]
I don't really understand how EnabledComponent is being used here, ill try to take a look too.

**Comment by zepumph** [comment]
I looks like this was a bug introduced in https://github.com/phetsims/axon/commit/a2730117d747a1f746a73941c66ad04b1e12cab8.


It looks like we need to make EnabledComponent parameteric to whether or not you can set the enabledProperty. I'll take a look.

**Comment by zepumph** [comment]
@samreid, @pixelzoom, @zepumph had a talk about public APIs for subcomponent properties (visibleProperty/enabledProperty/etc). Generally typescript behaves poorly here, because we have to parametrize the class to say if the underlying enabledProperty is settable or not. This would involve passing that parameter up from EnabledComponent -> ButtonModel -> forever up the hierarchy. Not to mention the need to do this for each subProperty of Node. Imagine: `Node<VisiblePropertyType, EnabledPropertyType, PickablePropertyType, InputEnabledPropertyType>`.

So we instead decided to punt. EnabledComponent accepts an IReadonlyProperty as an option, and this.enabledProperty is an `IProperty`. We type cast it internally. This is pretty excellent from a public API perspective, but it relies on runtime assertions when you try to set a derived property.

@chrisklus I didn't see your issue in NumberPlay anymore, and was able to remove the type cast in SpeechSynthesisAnnouncer. 

Please review.

**Comment by chrisklus** [comment]
@zepumph changes look great, and thanks for the explanation! I have not seen this issue on my end anymore. Closing.
